### ISSUE TITLE
No race results error

### ISSUE THREAD

**Issue by nathanieloffer** [daz/f1results#1]
So I've just installed F1Results on OS X 10.11.3 El Cap and regardless of what I enter I get either "No race results for <event> or Grand Prix not found. I did have a permissions error installing the gem so I've installed it into /usr/local alongside my brew packages but that shouldn't be an issue.

I've tried f1results 1984 monaco and f1results 2011 australia after seeing both in examples online and again nothing is working for me. I am using the Fish shell as my default but I also switched back to Bash on the off chance it might make a difference and it didn't I still saw the same errors.

**Comment by daz** [comment]
The previous version of formula1.com had an archive  of all the results.  They change the website and now there is only 2014 onwards.  I'll change the screenshot, cheers.

**Comment by nathanieloffer** [comment]
Thanks for the reply Darren but it's not working even for races "after"
2014.

I've searched for "f1results 2015 Melbourne" and "f1results 2015 Australia"
and both times I receive a "Grand Prix not found" error. The same with
f1results 2014 monaco and f1results 2014 australia.

Regards

Nathaniel
Twttr: @nathanieloffer

**Comment by daz** [comment]
Oh yeah, screenshot uses the old CLI too.

`f1results -c australia -y 2015 -e qualifying`

**Comment by nathanieloffer** [comment]
okay so I've tried that exact line and this is the output I get.

```
f1results -c australia -y 2015 -e qualifying
/Library/Ruby/Gems/2.0.0/gems/f1results-0.1.1/bin/f1results:17:in `<top (required)>': invalid option: -c (OptionParser::InvalidOption)
    from /usr/local/bin/f1results:23:in `load'
    from /usr/local/bin/f1results:23:in `<main>'
```

**Comment by daz** [comment]
tbh the CLI was an afterthought of this gem. I'll definitely fix this though.

**Comment by daz** [comment]
Proper example now, everything should be working in 0.6
